# -*- coding: utf-8 -*-
"""ApplianceEnergy Usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jxyYLZX6rBvnHAhlHBc6v7yw70P6hA8
"""

!pip install pandas numpy scikit-learn catboost matplotlib seaborn

from google.colab import files
files.upload()

!pip install kaggle

!ls

import pandas as pd

df = pd.read_csv("energydata_complete.csv")
print(df.shape)
df.head()

print("Columns:\n", df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values per Column:")
print(df.isnull().sum())

X = df.drop(columns=["Appliances"])
y = df["Appliances"]

print("Features:", X.shape)
print("Target:", y.shape)

# Fill missing values using median (robust & simple)
# Exclude non-numeric columns for median calculation as median cannot be computed for strings/objects.
X = X.select_dtypes(include=["number"])
X = X.fillna(X.median())

X = X.select_dtypes(include=["number"])

X = X.fillna(X.median())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

Q1 = X_train.quantile(0.25)
Q3 = X_train.quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

X_train = X_train.clip(lower=lower, upper=upper, axis=1)
X_test = X_test.clip(lower=lower, upper=upper, axis=1)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
sns.heatmap(X.corr(), cmap="coolwarm", linewidths=0.3)
plt.title("Feature Correlation Heatmap")
plt.show()

!pip install catboost

from sklearn.feature_selection import RFE
from catboost import CatBoostRegressor

rfe = RFE(
    estimator=CatBoostRegressor(
        iterations=200,
        learning_rate=0.1,
        depth=6,
        verbose=0
    ),
    n_features_to_select=15
)

rfe.fit(X_train, y_train)

selected_features = X_train.columns[rfe.support_]
X_train = X_train[selected_features]
X_test = X_test[selected_features]

print("Selected Features:", selected_features.tolist())

model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    verbose=100
)

model.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R² Score (acts like accuracy in regression): {r2:.3f}")

from sklearn.metrics import accuracy_score

try:
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)
except Exception as e:
    print("Accuracy cannot be used for regression problems.")
    print("Reason:", e)

print(f"R² Score: {r2:.3f}")

if r2 > 0:
    print("Model performs better than baseline mean predictor.")
else:
    print("Model does not improve over baseline.")

baseline_pred = np.full_like(y_test, y_train.mean())
baseline_r2 = r2_score(y_test, baseline_pred)

print("Baseline R²:", baseline_r2)
print("Model R²:", r2)

residuals = y_test - y_pred

plt.figure(figsize=(6,4))
sns.histplot(residuals, kde=True)
plt.title("Residual Distribution")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

# Select an unseen test sample
new_sample = X_test.iloc[[0]]
actual_value = y_test.iloc[0]

# Predict
predicted_value = model.predict(new_sample)[0]

# Error calculation
absolute_error = abs(actual_value - predicted_value)
percentage_error = (absolute_error / actual_value) * 100

print("Actual Value:", actual_value)
print("Predicted Value:", predicted_value)
print("Absolute Error:", absolute_error)
print(f"Percentage Error: {percentage_error:.2f}%")

import pandas as pd

feature_importance = model.get_feature_importance()
features = X_train.columns

importance_df = pd.DataFrame({
    "Feature": features,
    "Importance": feature_importance
}).sort_values(by="Importance", ascending=False)

importance_df.head(10)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.barh(importance_df["Feature"][:10], importance_df["Importance"][:10])
plt.gca().invert_yaxis()
plt.xlabel("Importance Score")
plt.title("Top 10 Important Features Affecting Energy Consumption")
plt.show()